### PR TITLE
Update deprecated selectors for 1.13.0

### PR DESCRIPTION
**Pull request by atkinchris**
This updates the deprecated selectors for Atom `1.13.0`.

### CODE REVIEW

**Comment by atkinchris** [comment]
Closed by accident when tidying up branches.

**Comment by mcastilho** [comment]
+1 for merging this

**Comment by Rusta** [comment]
+1

**Comment by nsilberman** [comment]
go go go :)

**Comment by atkinchris** [comment]
@nsilberman - I don't have permission to merge or make releases. Sure this will go out when @Stanko is ready!

**Comment by benjaminstout** [comment]
Can this PR be merged soon? Thanks!

**Comment by Stanko** [comment]
@benjaminstout I have no rights to merge this. Let's hope the owner will merge this PR. 

@schmittyjd ping 😄

**Comment by dannyec** [comment]
Is @schmittyjd absent? So many days when this deprecated appear :(

**Comment by schmittyjd** [comment]
@Stanko @dannyec Hey guys, been really busy focusing on other things going on with me. @stanko if you want permissions or ownership of the repo id be more than happy to put it in the hands of a more active member of the community! Merged 👍

**Pull request merged**
